# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'StarWars' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StarWars
  pod 'Alamofire', '~> 4.5'
  pod 'SDWebImage', '~> 4.0'
  
  target 'StarWarsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StarWarsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
